development:
  adapter: postgresql
  encoding: unicode
  database: cookit_development
  pool: 5
  username: marcin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cookit_test
  pool: 5
  username: marcin
  password:
